require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.bufferline")
require("core.plugin_config.gitsigns")
require("core.plugin_config.lualine")
require("core.plugin_config.lsp_config")
require("core.plugin_config.completions")
require("core.plugin_config.toggleterm")
require("core.plugin_config.hop")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.whichkey")
require("core.plugin_config.trouble")
require("core.plugin_config.stratify")
-- require("flutter-tools").setup{}
